image: docker:20.10.24

services:
  - docker:20.10.24-dind

before_script:
  - apk add python3
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  allow_failure:
      exit_codes: 2
  script:
    - python3 download.py
    - ls -l /app/Binaries/Editor/Linux/Release/
    - | 
      if [[ ! -d "app" ]]; then
        echo "app folder does not exist. Quitting job."
        exit 2  # Exit with success code 2 to indicate non-failure
      fi
    - export IMAGE_TAG=$(eval echo ${FLAX_VERSION//_/.}-${OS_PLATFORM})
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg OS=$OS --build-arg ENGINE_URL=$ENGINE_URL --build-arg OS_PLATFORM_URL=$OS_PLATFORM_URL .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  parallel:
    matrix:
      - OS_PLATFORM: [
          linux_amd64,
          windows_amd64,
          android_arm64,
          xboxone,
          windows_store,
        ]
