image: docker:latest

services:
  - docker:dind

before_script:
  - apk add python3

build:
  stage: build
  allow_failure:
      exit_codes: 2
  script:
    - python3 download.py
    - | 
      if [[ ! -d "app" ]]; then
        echo "app folder does not exist. Job failed."
        exit 2  # Exit with success code 2 to indicate non-failure
      fi
    - source _env
    - export IMAGE_TAG_VERSION_FULL=${OS_PLATFORM}-$FLAX_VERSION_FULL
    - export IMAGE_TAG_VERSION=${OS_PLATFORM}-$(eval echo ${FLAX_VERSION//_/.})
    - export IMAGE_TAG_LATEST=${OS_PLATFORM}-latest
    - |
      docker build \
      -t $CI_REGISTRY_IMAGE:$IMAGE_TAG_VERSION_FULL \
      -t $CI_REGISTRY_IMAGE:$IMAGE_TAG_VERSION \
      -t $CI_REGISTRY_IMAGE:$IMAGE_TAG_LATEST \
      --build-arg OS=$OS \
      --build-arg ENGINE_URL=$ENGINE_URL \
      --build-arg OS_PLATFORM_URL=$OS_PLATFORM_URL .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG_VERSION_FULL \
                  $CI_REGISTRY_IMAGE:$IMAGE_TAG_VERSION \
                  $CI_REGISTRY_IMAGE:$IMAGE_TAG_LATEST
  parallel:
    matrix:
      - OS_PLATFORM: [
          linux_amd64,
          # windows_amd64,
          # android_arm64,
          # xboxone,
          # windows_store,
        ]
